### ISSUE TITLE
Create Build issue.

### ISSUE THREAD

**Issue by Office-Murtaza** [skydoves/pokedex-compose#6]
e: file:///E:/composesamples/pokedex-compose-main/build-logic/convention/src/main/kotlin/com/skydoves/pokedex/compose/AndroidCompose.kt:13:35 5 type arguments expected for interface CommonExtension<BuildFeaturesT : BuildFeatures, BuildTypeT : BuildType, DefaultConfigT : DefaultConfig, ProductFlavorT : ProductFlavor, AndroidResourcesT : AndroidResources>
e: file:///E:/composesamples/pokedex-compose-main/build-logic/convention/src/main/kotlin/com/skydoves/pokedex/compose/AndroidCompose.kt:18:5 Unresolved reference: buildFeatures
e: file:///E:/composesamples/pokedex-compose-main/build-logic/convention/src/main/kotlin/com/skydoves/pokedex/compose/AndroidCompose.kt:19:7 Unresolved reference: compose

using android studio version

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0

**Comment by skydoves** [comment]
Hey @Office-Murtaza, you should use at least Android Studio Iguana instead of the Hedgehog.
If you still face the same issue after installing Android Studio Iguana, please reopen it. Thank you!
